version: '3.8'
services:
  rangeconnectbackend:
    build: .
    hostname: 'rangeconnectbackend'
    container_name: 'rangeconnectbackend'
    restart: always
    environment:
      - DATABASE_HOST=192.168.234.118
      - DATABASE_USER=rangeconnect
      - DATABASE_PASS=rangeconnect
      - DATABASE_DB=rangeconnect
    ports:
      - 8000:8000
