"""Added schema and initial tables

Revision ID: 50826c0861a4
Revises:
Create Date: 2024-01-06 00:41:59.503753

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '50826c0861a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='rcb'
    )
    op.create_index(op.f('ix_rcb_country_id'), 'country', ['id'], unique=False, schema='rcb')
    op.create_table('range_manufactor',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='rcb'
    )
    op.create_index(op.f('ix_rcb_range_manufactor_id'), 'range_manufactor', ['id'], unique=False, schema='rcb')
    op.create_table('shooting_club',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('shortname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('country_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['rcb.country.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='rcb'
    )
    op.create_index(op.f('ix_rcb_shooting_club_id'), 'shooting_club', ['id'], unique=False, schema='rcb')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rcb_shooting_club_id'), table_name='shooting_club', schema='rcb')
    op.drop_table('shooting_club', schema='rcb')
    op.drop_index(op.f('ix_rcb_range_manufactor_id'), table_name='range_manufactor', schema='rcb')
    op.drop_table('range_manufactor', schema='rcb')
    op.drop_index(op.f('ix_rcb_country_id'), table_name='country', schema='rcb')
    op.drop_table('country', schema='rcb')
    # ### end Alembic commands ###