"""Adding seed data to database

Revision ID: af9eb26ee078
Revises: 4c712d84d5c4
Create Date: 2024-01-07 02:28:31.112255

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import uuid


# revision identifiers, used by Alembic.
revision = 'af9eb26ee078'
down_revision = '4c712d84d5c4'
branch_labels = None
depends_on = None

# Generate a random UUID
ISSF10ARF_uuid = uuid.uuid4()
ISSF10APF_uuid = uuid.uuid4()

european_countries = [
    ('AL', 'Albania', str(uuid.uuid4())),
    ('AD', 'Andorra', str(uuid.uuid4())),
    ('AM', 'Armenia', str(uuid.uuid4())),
    ('AT', 'Austria', str(uuid.uuid4())),
    ('AZ', 'Azerbaijan', str(uuid.uuid4())),
    ('BY', 'Belarus', str(uuid.uuid4())),
    ('BE', 'Belgium', str(uuid.uuid4())),
    ('BA', 'Bosnia and Herzegovina', str(uuid.uuid4())),
    ('BG', 'Bulgaria', str(uuid.uuid4())),
    ('HR', 'Croatia', str(uuid.uuid4())),
    ('CY', 'Cyprus', str(uuid.uuid4())),
    ('CZ', 'Czech Republic', str(uuid.uuid4())),
    ('DK', 'Denmark', str(uuid.uuid4())),
    ('EE', 'Estonia', str(uuid.uuid4())),
    ('FI', 'Finland', str(uuid.uuid4())),
    ('FR', 'France', str(uuid.uuid4())),
    ('GE', 'Georgia', str(uuid.uuid4())),
    ('DE', 'Germany', str(uuid.uuid4())),
    ('GR', 'Greece', str(uuid.uuid4())),
    ('HU', 'Hungary', str(uuid.uuid4())),
    ('IS', 'Iceland', str(uuid.uuid4())),
    ('IE', 'Ireland', str(uuid.uuid4())),
    ('IT', 'Italy', str(uuid.uuid4())),
    ('KZ', 'Kazakhstan', str(uuid.uuid4())),
    ('XK', 'Kosovo', str(uuid.uuid4())),
    ('LV', 'Latvia', str(uuid.uuid4())),
    ('LI', 'Liechtenstein', str(uuid.uuid4())),
    ('LT', 'Lithuania', str(uuid.uuid4())),
    ('LU', 'Luxembourg', str(uuid.uuid4())),
    ('MK', 'North Macedonia', str(uuid.uuid4())),
    ('MT', 'Malta', str(uuid.uuid4())),
    ('MD', 'Moldova', str(uuid.uuid4())),
    ('MC', 'Monaco', str(uuid.uuid4())),
    ('ME', 'Montenegro', str(uuid.uuid4())),
    ('NL', 'Netherlands', str(uuid.uuid4())),
    ('NO', 'Norway', str(uuid.uuid4())),
    ('PL', 'Poland', str(uuid.uuid4())),
    ('PT', 'Portugal', str(uuid.uuid4())),
    ('RO', 'Romania', str(uuid.uuid4())),
    ('RU', 'Russia', str(uuid.uuid4())),
    ('SM', 'San Marino', str(uuid.uuid4())),
    ('RS', 'Serbia', str(uuid.uuid4())),
    ('SK', 'Slovakia', str(uuid.uuid4())),
    ('SI', 'Slovenia', str(uuid.uuid4())),
    ('ES', 'Spain', str(uuid.uuid4())),
    ('SE', 'Sweden', str(uuid.uuid4())),
    ('CH', 'Switzerland', str(uuid.uuid4())),
    ('TR', 'Turkey', str(uuid.uuid4())),
    ('UA', 'Ukraine', str(uuid.uuid4())),
    ('GB', 'United Kingdom', str(uuid.uuid4())),
    ('VA', 'Vatican City', str(uuid.uuid4())),
]

range_manufactor = [
    ('Megalink', str(uuid.uuid4())),
    ('SIUS', str(uuid.uuid4())),
]

discipline = [
    ('ISSF 10m AR Final', 'ISSF10ARF', 'ENABLED', f'{ISSF10ARF_uuid}'),
    ('ISSF 10m AP Final', 'ISSF10APF', 'ENABLED', f'{ISSF10APF_uuid}'),
]

discipline_series = [
    (1, 'Sighters', 'SIGHT', 300, 'NULL', 'NULL', 'NULL', 'NULL', f'{uuid.uuid4()}', f'{ISSF10ARF_uuid}'),
    (2, '1-5', 'MATCH', 250, 5, False, False, 'NULL', f'{uuid.uuid4()}', f'{ISSF10ARF_uuid}'),
    (3, '6-10', 'MATCH', 250, 5, False, False, 'NULL', f'{uuid.uuid4()}', f'{ISSF10ARF_uuid}'),
    (4, '11-12', 'MATCH', 50, 2, True, True, 1, f'{uuid.uuid4()}', f'{ISSF10ARF_uuid}'),
    (5, '13-14', 'MATCH', 50, 2, True, True, 1, f'{uuid.uuid4()}', f'{ISSF10ARF_uuid}'),
    (6, '15-16', 'MATCH', 50, 2, True, True, 1, f'{uuid.uuid4()}', f'{ISSF10ARF_uuid}'),
    (7, '17-18', 'MATCH', 50, 2, True, True, 1, f'{uuid.uuid4()}', f'{ISSF10ARF_uuid}'),
    (8, '19-20', 'MATCH', 50, 2, True, True, 1, f'{uuid.uuid4()}', f'{ISSF10ARF_uuid}'),
    (9, '21-22', 'MATCH', 50, 2, True, True, 1, f'{uuid.uuid4()}', f'{ISSF10ARF_uuid}'),
    (10, '23-24', 'MATCH', 50, 2, True, True, 1, f'{uuid.uuid4()}', f'{ISSF10ARF_uuid}'),
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
     for data in european_countries:
        op.execute(
            f"INSERT INTO country (code, name, id) VALUES "
            f"('{data[0]}', '{data[1]}', '{data[2]}')"
        )
     for data in range_manufactor:
        op.execute(
            f"INSERT INTO range_manufactor (name, id) VALUES "
            f"('{data[0]}', '{data[1]}')"
        )
     for data in discipline:
        op.execute(
            f"INSERT INTO discipline (name, shortname, status, id) VALUES "
            f"('{data[0]}', '{data[1]}', '{data[2]}', '{data[3]}')"
        )
     for data in discipline_series:
        op.execute(
            f"INSERT INTO discipline_series (series, name, type, time, number_of_shots, single_shots, elimination, shooters_to_eliminate, id, discipline_id) VALUES "
            f"({data[0]}, '{data[1]}', '{data[2]}', {data[3]}, {data[4]}, {data[5]}, {data[6]}, {data[7]}, '{data[8]}', '{data[9]}')"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###