"""Adding seed data to database

Revision ID: af9eb26ee078
Revises: 4c712d84d5c4
Create Date: 2024-01-07 02:28:31.112255

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import uuid


# revision identifiers, used by Alembic.
revision = 'af9eb26ee078'
down_revision = '4c712d84d5c4'
branch_labels = None
depends_on = None

# Generate a random UUID
ISSF10ARF_uuid = uuid.uuid4()
ISSF10APF_uuid = uuid.uuid4()



discipline = [
    ('ISSF 10m AR Final', 'ISSF10ARF', 'ENABLED', f'{ISSF10ARF_uuid}'),
    ('ISSF 10m AP Final', 'ISSF10APF', 'ENABLED', f'{ISSF10APF_uuid}'),
]

discipline_series = [
    (1, 'Sighters', 'SIGHT', 300, 'NULL', 'NULL', 'NULL', 'NULL', f'{uuid.uuid4()}', f'{ISSF10ARF_uuid}'),
    (2, '1-5', 'MATCH', 250, 5, False, False, 'NULL', f'{uuid.uuid4()}', f'{ISSF10ARF_uuid}'),
    (3, '6-10', 'MATCH', 250, 5, False, False, 'NULL', f'{uuid.uuid4()}', f'{ISSF10ARF_uuid}'),
    (4, '11-12', 'MATCH', 50, 2, True, True, 1, f'{uuid.uuid4()}', f'{ISSF10ARF_uuid}'),
    (5, '13-14', 'MATCH', 50, 2, True, True, 1, f'{uuid.uuid4()}', f'{ISSF10ARF_uuid}'),
    (6, '15-16', 'MATCH', 50, 2, True, True, 1, f'{uuid.uuid4()}', f'{ISSF10ARF_uuid}'),
    (7, '17-18', 'MATCH', 50, 2, True, True, 1, f'{uuid.uuid4()}', f'{ISSF10ARF_uuid}'),
    (8, '19-20', 'MATCH', 50, 2, True, True, 1, f'{uuid.uuid4()}', f'{ISSF10ARF_uuid}'),
    (9, '21-22', 'MATCH', 50, 2, True, True, 1, f'{uuid.uuid4()}', f'{ISSF10ARF_uuid}'),
    (10, '23-24', 'MATCH', 50, 2, True, True, 1, f'{uuid.uuid4()}', f'{ISSF10ARF_uuid}'),
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
     for data in discipline:
        op.execute(
            f"INSERT INTO discipline (name, shortname, status, id) VALUES "
            f"('{data[0]}', '{data[1]}', '{data[2]}', '{data[3]}')"
        )
     for data in discipline_series:
        op.execute(
            f"INSERT INTO discipline_series (series, name, type, time, number_of_shots, single_shots, elimination, shooters_to_eliminate, id, discipline_id) VALUES "
            f"({data[0]}, '{data[1]}', '{data[2]}', {data[3]}, {data[4]}, {data[5]}, {data[6]}, {data[7]}, '{data[8]}', '{data[9]}')"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###