"""Adding data for development environment

Revision ID: eb0bee64c83f
Revises: af9eb26ee078
Create Date: 2024-01-07 16:19:36.094983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
import sqlmodel
import uuid

# revision identifiers, used by Alembic.
revision = 'eb0bee64c83f'
down_revision = 'af9eb26ee078'
branch_labels = None
depends_on = None


# Generate a random UUID
ISSF10ARF_uuid = uuid.uuid4()
ISSF10APF_uuid = uuid.uuid4()

shooting_club = [
    ('Viborg Skytteforening', 'VSF', str(uuid.uuid4()), 'DK'),
]

shooting_range = [
    ('10m', 10, '1', 'EBA2ED57-BF56-47DE-91F8-DEA032843FE3', 'Viborg Skytteforening', 'Megalink'),
]

event = [
    ('Viborg Open Air', '2024-01-08T14:30:00', 'PLANNED', str(uuid.uuid4()), 'Viborg Skytteforening'),
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    for data in shooting_club:
        # Retrieve the ID for the country and store it in the dictionary
        country_id = op.get_bind().execute(text(
            f"SELECT id FROM country WHERE code = '{data[3]}'"
        )).scalar()

        op.execute(
            f"INSERT INTO shooting_club (name, shortname, id, country_id) VALUES "
            f"('{data[0]}', '{data[1]}', '{data[2]}', '{country_id}')"
        )
    
    for data in shooting_range:
        # Retrieve the ID for the country and store it in the dictionary
        shooting_club_id = op.get_bind().execute(text(
            f"SELECT id FROM shooting_club WHERE name = '{data[4]}'"
        )).scalar()

        shooting_club_id = shooting_club_id if shooting_club_id is not None else None

        range_manufactor_id = op.get_bind().execute(text(
            f"SELECT id FROM range_manufactor WHERE name = '{data[5]}'"
        )).scalar()

        range_manufactor_id = range_manufactor_id if range_manufactor_id is not None else None

        op.execute(
            f"INSERT INTO shooting_range (name, lanes, first_lane, id, shooting_club_id, range_manufactor_id) VALUES "
            f"('{data[0]}', {data[1]}, '{data[2]}', '{data[3]}', '{shooting_club_id}', '{range_manufactor_id}')"
        )

    for data in event:
        # Retrieve the ID for the country and store it in the dictionary
        shooting_club_id = op.get_bind().execute(text(
            f"SELECT id FROM shooting_club WHERE name = '{data[4]}'"
        )).scalar()

        op.execute(
            f"INSERT INTO event (name, startdate, status, id, shooting_club_id) VALUES "
            f"('{data[0]}', '{data[1]}', '{data[2]}', '{data[3]}', '{shooting_club_id}')"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###